version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: url_shortener_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: url_shortener
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - url_shortener_network

  redis:
    image: redis:7.0-alpine
    container_name: url_shortener_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - url_shortener_network

  app:
    build: .
    container_name: url_shortener_app
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - MYSQL_HOST=mysql
      - REDIS_HOST=redis
    networks:
      - url_shortener_network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  url_shortener_network:
    driver: bridge
