server:
  port: 8080
  mode: debug  # debug, release

mysql:
  host: localhost
  port: 3306
  username: root
  password: root123
  database: url_shortener
  max_idle_conns: 10
  max_open_conns: 100

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 100

bloom_filter:
  capacity: 10000000
  false_positive_rate: 0.01

snowflake:
  datacenter_id: 1
  worker_id: 1

rate_limit:
  enabled: true
  strategy: "sliding_window"  # fixed_window, sliding_window, token_bucket
  global:
    limit: 100              # Maximum requests
    window: 60              # Time window in seconds
  endpoints:
    # Custom limits for specific endpoints
    - path: "/api/v1/shorten"
      limit: 10             # 10 requests
      window: 60            # per 60 seconds
    - path: "/:short_code"
      limit: 50             # 50 redirects
      window: 60            # per 60 seconds
